database:
  username: cemindmapuser
  password: cemindmappw
  host: localhost
  port: 5432 # change this value
  databaseName: cemindmapdb
# conduit db generate
# conduit db upgrade --connect postgres://cemindmapuser:cemindmappw@localhost:5432/cemindmapdb
